name: "Deploy"

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        environment: staging
        timeout-minutes: 15
        outputs:
            imageId: ${{ steps.image.outputs.imageId}}
        env:
            ENVIRONMENT_NAME: staging
        defaults:
            run:
                shell: bash
        steps:
            - id: failed_step
              run: exit 1
            - id: image
              if: ${{ failure() }}
              run: |
                  IMAGE=1234
                  echo "::set-output name=imageId::ecr.docker:efi/something:$IMAGE"
    stage:
        name: "stage"
        runs-on: ubuntu-latest
        environment: approval-required
        needs:
            - build
        timeout-minutes: 15
        env:
            ENVIRONMENT_NAME: staging
        defaults:
            run:
                shell: bash
        steps:
            - id: image
              run: |
                  echo "manually approved"
    prod:
        name: "Prod"
        needs:
            - build
            - stage
        runs-on: ubuntu-latest
        environment: approval-required
        steps:
            - run: |
                  echo Image Is ${{needs.build.outputs.imageId}}
