name: "Deploy"

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    staging:
        name: "Stage"
        runs-on: ubuntu-latest
        environment: staging
        timeout-minutes: 15
        outputs:
            imageId: ${{ steps.image.outputs.imageId}}
        env:
            ENVIRONMENT_NAME: staging
        defaults:
            run:
                shell: bash
        steps:
            - id: image
              run: |
                  echo "::set-output name=imageId::ecr.docker:efi/something:123"
    terraform-apply:
        name: "Terraform apply"
        runs-on: ubuntu-latest
        environment: approval-required
        timeout-minutes: 15
        env:
            ENVIRONMENT_NAME: staging
        defaults:
            run:
                shell: bash
        steps:
            - id: image
              run: |
                  echo "manually approved"
    prod:
        name: "Prod"
        needs:
            - staging
            - terraform-apply
        runs-on: ubuntu-latest
        environment: approval-required
        steps:
            - run: |
                  echo Image Is ${{needs.staging.outputs.imageId}}
